
INSERT INTO TB_VEICULO (ID_VEICULO, NM_VEICULO, DSC_VEICULO, NM_MARCA, DT_ANO, ST_VEICULO) values (110, 'Up', 'Otimo carro', 'Volkswagem', 2021, false)
INSERT INTO TB_VEICULO (ID_VEICULO, NM_VEICULO, DSC_VEICULO, NM_MARCA, DT_ANO, ST_VEICULO) values (111, 'Jetta', 'Otimo carro', 'Volkswagem', 2022, false)
INSERT INTO TB_VEICULO (ID_VEICULO, NM_VEICULO, DSC_VEICULO, NM_MARCA, DT_ANO, ST_VEICULO) values (112, 'Golf', 'Otimo carro', 'Volkswagem', 2015, false)
INSERT INTO TB_VEICULO (ID_VEICULO, NM_VEICULO, DSC_VEICULO, NM_MARCA, DT_ANO, ST_VEICULO) values (113, 'Cruze', 'Otimo carro', 'Chevrolet', 2019, false)
INSERT INTO TB_VEICULO (ID_VEICULO, NM_VEICULO, DSC_VEICULO, NM_MARCA, DT_ANO, ST_VEICULO) values (114, 'Honda Civic', 'Otimo carro', 'Honda', 2020, false)
INSERT INTO TB_VEICULO (ID_VEICULO, NM_VEICULO, DSC_VEICULO, NM_MARCA, DT_ANO, ST_VEICULO) values (115, 'Honda Fit', 'Otimo carro', 'Honda', 2005, true)
INSERT INTO TB_VEICULO (ID_VEICULO, NM_VEICULO, DSC_VEICULO, NM_MARCA, DT_ANO, ST_VEICULO) values (116, 'IX35', 'Otimo carro', 'HIUNDAY', 2021, true)